version: '3.7'

services:  
  model_contributor_decentral:
    image: decentralml_client:latest
    container_name: model_contributor_decentral
    volumes:
      - $HOME/DecentralML/assets/:/decentralml/assets
    environment:
      - SOCKET_URL=ws://node_decentral:9944
      - ASSETS_FOLDER=/decentralml/assets/
      - IPFS_API_KEY=2YBXx5wpHlPPOrL91T8VwedHdz7
      - IPFS_API_SECRET=497193a34170a89435eb4d9582dab729
      - IPFS_END_POINT=https://ipfs.infura.io:5001
      - EMULATE_IPFS=True
    stdin_open: true 
    tty: true