version: '3.7'

services:
  node_decentral:
    image: decentralml_node:latest
    container_name: node_decentralml
    ports:
      - 9944:9944
      - 9615:9615
    stdin_open: true 
    tty: true
  client_decentral:
    image: decentralml_client:latest
    container_name: client_decentralml
    volumes:
      - $HOME/decentralml/assets/:/decentralml/assets
      - $HOME/decentralml/remote/:/decentralml/remote
    environment:
      - SOCKET_URL=ws://node_decentral:9944
      - ASSETS_FOLDER=/decentralml/assets/
      - IPFS_API_KEY=2YBXx5wpHlPPOrL91T8VwedHdz7
      - IPFS_API_SECRET=497193a34170a89435eb4d9582dab729
      - IPFS_END_POINT=https://ipfs.infura.io:5001
      - DECENTRALML_ROLE=model_creator
      - EMULATE_IPFS=True
      - REMOTE_FOLDER=/decentralml/remote
    links:
      - "node_decentral:node"
    stdin_open: true 
    tty: true
