[tool.poetry]
name = "decentralml_client"
version = "1.0"
authors = ["Mathias Ciliberto <mathias.ciliberto@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
substrate-interface=">=1.7.4"
requests="2.31"