[tool.poetry]
name = "decentralml_client"
version = "1.0"
authors = ["Mathias Ciliberto <mathias.ciliberto@gmail.com>"]
description = "Python client for DecentralML"
readme = "README.md"

[tool.poetry.dependencies]
python=">=3.10"
substrate-interface=">=1.7.4"
requests="2.31"